version: '3.8'

services:
  backend:
    build:
      target: development
    profiles:
      - dev
    volumes:
      - ./backend:/app
    environment:
      RAILS_ENV: development

  adminer:
    image: adminer:4.8.1
    profiles:
      - dev
    ports:
      - "8080:8080"
    networks:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
